project_id = "mbbxaejkwayrkstyrudr"

[functions.generate-insights]
verify_jwt = true

[functions.extract-products-from-image]
verify_jwt = true

[functions.virtual-try-on]
verify_jwt = false

[functions.reset-password]
verify_jwt = false
